"""removed extra genres column

Revision ID: 3e9c68fd188a
Revises: 37b352dbf63b
Create Date: 2021-11-10 19:55:27.379315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9c68fd188a'
down_revision = '37b352dbf63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', sa.Column('genres', sa.String(120), nullable=True))
    # ### end Alembic commands ###
