"""empty message

Revision ID: 61dd6f5a0430
Revises: b363f7447fdc
Create Date: 2021-11-13 00:19:40.385236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dd6f5a0430'
down_revision = 'b363f7447fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'tmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('tmp', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
