"""empty message

Revision ID: b363f7447fdc
Revises: d15fdab561bf
Create Date: 2021-11-13 00:13:37.534674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b363f7447fdc'
down_revision = 'd15fdab561bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('tmp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'tmp')
    # ### end Alembic commands ###
